heat_template_version: 2014-10-16
#
# 'openstack stack create -t elasticsearch.yaml -e elasticsearch_env.yaml <stackName>'
# 

description: Simple template to deploy an elasticsearch stack 

parameters:
 public_network:
  type: string
  default: ext-net 
 ssh_keys:
  type: comma_delimited_list
 instance_name:
  type: string
  default: elasticsearch
 image: 
  type: string
  default: Ubuntu 18.04 LTS - 2018-08-10
 flavor: 
  type: string
  default: l1.medium

resources:
  allow_ssh:
    type: OS::Neutron::SecurityGroup
    properties:
      description: allow incoming SSH and ICMP traffic from anywhere.
      name: allow incoming traffic, tcp port 22 and icmp
      rules: 
        - { direction: ingress, remote_ip_prefix: 0.0.0.0/0, port_range_min: 22, port_range_max: 22, protocol: tcp } 
        - { direction: ingress, remote_ip_prefix: 0.0.0.0/0, protocol: icmp } 

  allow_webtraffic:
    type: OS::Neutron::SecurityGroup
    properties:
      description: allow incoming web traffic via http from anywhere. 
      name: allow incoming traffic, tcp port 80
      rules: 
        - { direction: ingress, remote_ip_prefix: 0.0.0.0/0, port_range_min: 80, port_range_max: 80, protocol: tcp } 
        - { direction: ingress, remote_ip_prefix: 0.0.0.0/0, port_range_min: 443, port_range_max: 443, protocol: tcp } 

  allow_jiratraffic:
    type: OS::Neutron::SecurityGroup
    properties:
      description: allow incoming web traffic via http from anywhere. 
      name: allow incoming traffic, tcp port 8080
      rules: 
        - { direction: ingress, remote_ip_prefix: 0.0.0.0/0, port_range_min: 8080, port_range_max: 8080, protocol: tcp } 

  host:
    type: OS::Nova::Server
    properties:
      name: { get_param: instance_name } 
      user_data_format: RAW
      user_data: { get_resource: cloud-init-config }    
      image: { get_param: image }
      flavor: { get_param: flavor }
      networks:
        - port: { get_resource: port }

  cloud-init-config:
   # cloud init resource
   type: OS::Heat::CloudConfig
   properties:
     cloud_config:
       manage_etc_hosts: true
       fqdn: elasticsearch.aboter.de
       write_files:
         -  content: { get_file: scripts/install_elasticsearch.sh }
            permissions: 700
            path: /root/install_elasticsearch.sh
       runcmd:
         - /root/install_elasticsearch.sh
       users:
         -  name: syseleven
            gecos:  Service user
            lock-passwd: false
            sudo: ALL=(ALL) NOPASSWD:ALL
            shell: /bin/bash
            ssh-authorized-keys: { get_param: ssh_keys }
       packages:
         - curl

             
  port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: net}
      security_groups: [ get_resource: allow_ssh, get_resource: allow_webtraffic ]

  net:
    type: OS::Neutron::Net
    properties: 
      name: elasticsearchserver-net

  subnet:
    type: OS::Neutron::Subnet
    properties:
      name: elasticsearchserver-subnet
      dns_nameservers:
        - 8.8.8.8
        - 8.8.4.4
      network: {get_resource: net}
      ip_version: 4
      cidr: 10.0.0.0/24
      allocation_pools:
      - {start: 10.0.0.10, end: 10.0.0.250}

  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info: {"network": { get_param: public_network }}
      name: elasticsearchserver-router

  router_subnet_bridge:
    type: OS::Neutron::RouterInterface
    depends_on: subnet
    properties:
      router: { get_resource: router }
      subnet: { get_resource: subnet }

  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: public_network }
      port_id: { get_resource: port }
